blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/febdoctor/sthenos-embedded-toolkit/discussions
    about: Please ask and answer questions in the discussions section
  - name: Documentation
    url: https://github.com/febdoctor/sthenos-embedded-toolkit/blob/main/README.md
    about: Check the README for build instructions and supported architectures